// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

namespace Match.Actions {
	public interface IAction {
		void initWithActionManager(CGameActionManager aManager, CField aIconField);

		void doUpdateActionParam(Hashtable aData);

		bool validation();

		void startAction();

		void setDelegate(Match.Actions.Delegate aDelegate);

		GameNotificationEvents getActionEvent();
	}
}