// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public delegate void MatchActionDelegate(IMatchAction aAction);

public interface IMatchAction
{
	void initWithActionManager(CGameActionManager aManager, CField aIconField);

	void doUpdateActionParam(Hashtable aData);

	bool validation();

	void startAction();

	void updateting();

	void setDelegate(MatchActionDelegate aDelegate);

	GameNotificationEvents getActionEvent();
}


